version: '3.8'

services:
  auradoc_frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: auradoc_frontend
    ports:
      - "5173:5173"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - API_DOTNET_URL=${API_DOTNET_URL:-http://localhost:5000}
      - API_BACKEND_URL=${API_BACKEND_URL:-http://localhost:3000}
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    # Instalamos dependencias y corremos vite exponiendo al host
    command: bash -c "pnpm install --config.minimum-release-age=0 && pnpm run dev --host 0.0.0.0"
